# Generated by Django 2.2.3 on 2021-11-01 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0002_livros_mostrar'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/%y/%m/'),
        ),
    ]
