# Generated by Django 2.2.3 on 2021-11-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0004_livros_livro'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeusLivros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('livro_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='livros',
            name='livro',
            field=models.FileField(blank=True, upload_to='pdfs/%y/%m/'),
        ),
    ]
