# Generated by Django 2.2.3 on 2021-11-07 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0005_auto_20211107_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meus_Livros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('livro_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='MeusLivros',
        ),
    ]
