# Generated by Django 2.2.3 on 2021-11-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0007_auto_20211108_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeusLivro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livro', models.ManyToManyField(null=True, to='paginas.Livros')),
            ],
        ),
        migrations.DeleteModel(
            name='MeusLivros',
        ),
    ]
