# Generated by Django 2.2.3 on 2021-11-08 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0008_auto_20211108_1218'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MeusLivro',
        ),
    ]
