# Generated by Django 5.0.4 on 2024-05-07 01:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0009_delete_meuslivro'),
    ]

    operations = [
        migrations.CreateModel(
            name='pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=80)),
                ('foto', models.ImageField(blank=True, upload_to='fotos/%y/%m/')),
                ('nome', models.CharField(max_length=80)),
                ('raca', models.CharField(max_length=80)),
                ('tutor', models.CharField(max_length=180)),
                ('email', models.CharField(max_length=260)),
                ('telefone', models.CharField(max_length=80)),
                ('cpf', models.CharField(max_length=260)),
                ('endereco', models.CharField(max_length=150)),
                ('data_acolhimento', models.DateTimeField(default=django.utils.timezone.now)),
                ('historico_medico', models.CharField(blank=True, max_length=500000)),
            ],
        ),
    ]
