# Generated by Django 5.0.4 on 2024-05-07 01:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0010_pet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livros2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('editora', models.CharField(max_length=80)),
                ('descricao', models.TextField(blank=True)),
                ('ano_Lancamento', models.DateTimeField(default=django.utils.timezone.now)),
                ('mostrar', models.BooleanField(default=True)),
                ('foto', models.ImageField(blank=True, upload_to='fotos/%y/%m/')),
                ('livro', models.FileField(blank=True, upload_to='pdfs/%y/%m/')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='paginas.categoria')),
            ],
        ),
    ]
