# Generated by Django 5.0.4 on 2024-05-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0011_livros2'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='status',
            field=models.CharField(choices=[('Tutor não localizado', 'Tutor não localizado'), ('Tutor localizado', 'Tutor localizado'), ('Retirado pelo tutor', 'Retirado pelo tutor')], default='Disponível', max_length=80),
        ),
    ]
