# Generated by Django 5.0.4 on 2024-05-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0012_livros_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='status',
            field=models.CharField(choices=[('Tutor não localizado', 'Tutor não localizado'), ('Tutor localizado', 'Tutor localizado'), ('Retirado pelo tutor', 'Retirado pelo tutor')], default=' ', max_length=80),
        ),
    ]
