# Generated by Django 5.0.4 on 2024-05-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0013_alter_livros_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livros',
            old_name='ano_Lancamento',
            new_name='data_acolhimento',
        ),
        migrations.RemoveField(
            model_name='livros',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='livros',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='livros',
            name='editora',
        ),
        migrations.RemoveField(
            model_name='livros',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='livros',
            name='livro',
        ),
        migrations.RemoveField(
            model_name='livros',
            name='mostrar',
        ),
        migrations.AddField(
            model_name='livros',
            name='cpf',
            field=models.CharField(choices=[('Tutor não localizado', 'Tutor não localizado'), ('Tutor localizado', 'Tutor localizado'), ('Retirado pelo tutor', 'Retirado pelo tutor')], default='xxx.xxx.xxx-xx', max_length=260),
        ),
        migrations.AddField(
            model_name='livros',
            name='email',
            field=models.CharField(choices=[('Tutor não localizado', 'Tutor não localizado'), ('Tutor localizado', 'Tutor localizado'), ('Retirado pelo tutor', 'Retirado pelo tutor')], default='Email pendente', max_length=260),
        ),
        migrations.AddField(
            model_name='livros',
            name='endereco',
            field=models.CharField(choices=[('Tutor não localizado', 'Tutor não localizado'), ('Tutor localizado', 'Tutor localizado'), ('Retirado pelo tutor', 'Retirado pelo tutor')], default='Sem endereço', max_length=150),
        ),
        migrations.AddField(
            model_name='livros',
            name='historico_medico',
            field=models.CharField(blank=True, max_length=500000),
        ),
        migrations.AddField(
            model_name='livros',
            name='raca',
            field=models.CharField(choices=[('Tutor não localizado', 'Tutor não localizado'), ('Tutor localizado', 'Tutor localizado'), ('Retirado pelo tutor', 'Retirado pelo tutor')], default='Raça pendente', max_length=80),
        ),
        migrations.AddField(
            model_name='livros',
            name='telefone',
            field=models.CharField(choices=[('Tutor não localizado', 'Tutor não localizado'), ('Tutor localizado', 'Tutor localizado'), ('Retirado pelo tutor', 'Retirado pelo tutor')], default='Telefone pendente', max_length=80),
        ),
        migrations.AddField(
            model_name='livros',
            name='tutor',
            field=models.CharField(choices=[('Tutor não localizado', 'Tutor não localizado'), ('Tutor localizado', 'Tutor localizado'), ('Retirado pelo tutor', 'Retirado pelo tutor')], default='Tutor pendente', max_length=180),
        ),
        migrations.AlterField(
            model_name='livros',
            name='nome',
            field=models.CharField(choices=[('Tutor não localizado', 'Tutor não localizado'), ('Tutor localizado', 'Tutor localizado'), ('Retirado pelo tutor', 'Retirado pelo tutor')], default='Sem nome', max_length=80),
        ),
        migrations.AlterField(
            model_name='livros',
            name='status',
            field=models.CharField(choices=[('Tutor não localizado', 'Tutor não localizado'), ('Tutor localizado', 'Tutor localizado'), ('Retirado pelo tutor', 'Retirado pelo tutor')], default='Status pendente', max_length=80),
        ),
        migrations.DeleteModel(
            name='Livros2',
        ),
    ]
