# Generated by Django 5.0.4 on 2024-05-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0014_rename_ano_lancamento_livros_data_acolhimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='cpf',
            field=models.CharField(default='xxx.xxx.xxx-xx', max_length=260),
        ),
        migrations.AlterField(
            model_name='livros',
            name='email',
            field=models.CharField(default='Email pendente', max_length=260),
        ),
        migrations.AlterField(
            model_name='livros',
            name='endereco',
            field=models.CharField(default='Sem endereço', max_length=150),
        ),
        migrations.AlterField(
            model_name='livros',
            name='nome',
            field=models.CharField(default='Sem nome', max_length=80),
        ),
        migrations.AlterField(
            model_name='livros',
            name='raca',
            field=models.CharField(default='Raça pendente', max_length=80),
        ),
        migrations.AlterField(
            model_name='livros',
            name='telefone',
            field=models.CharField(default='Telefone pendente', max_length=80),
        ),
        migrations.AlterField(
            model_name='livros',
            name='tutor',
            field=models.CharField(default='Tutor pendente', max_length=180),
        ),
    ]
