# Generated by Django 5.0.4 on 2024-05-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0015_alter_livros_cpf_alter_livros_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/%y/%m/'),
        ),
    ]
