# Generated by Django 5.0.4 on 2024-05-08 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0017_livros2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Livros',
            new_name='Pets',
        ),
        migrations.RemoveField(
            model_name='livros2',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='pet',
        ),
        migrations.DeleteModel(
            name='Livros2',
        ),
    ]
