# Generated by Django 5.0.4 on 2024-05-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0018_rename_livros_pets_remove_livros2_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pets',
            name='local',
            field=models.CharField(default='Email pendente', max_length=500),
        ),
    ]
