# Generated by Django 5.0.4 on 2024-05-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0019_pets_local'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pets',
            name='local',
        ),
        migrations.AddField(
            model_name='pets',
            name='local_resgate',
            field=models.CharField(default='Local não informado', max_length=500),
        ),
    ]
