# Generated by Django 5.0.4 on 2024-05-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0020_remove_pets_local_pets_local_resgate'),
    ]

    operations = [
        migrations.AddField(
            model_name='pets',
            name='especie',
            field=models.CharField(choices=[('Cachorro', 'Cachorro'), ('Gato', 'Gato'), ('Outra', 'Outra')], default='Outra', max_length=80),
        ),
        migrations.AddField(
            model_name='pets',
            name='porte',
            field=models.CharField(choices=[('P', 'P'), ('M', 'M'), ('G', 'G')], default='Outra', max_length=80),
        ),
        migrations.AddField(
            model_name='pets',
            name='sexo',
            field=models.CharField(choices=[('Macho', 'Macho'), ('Fêmea', 'Fêmea')], default='Outra', max_length=80),
        ),
        migrations.AlterField(
            model_name='pets',
            name='raca',
            field=models.CharField(choices=[('Labrador Retriever', 'Labrador Retriever'), ('Golden Retriever', 'Golden Retriever'), ('Pastor Alemão', 'Pastor Alemão'), ('Bulldog Francês', 'Bulldog Francês'), ('Beagle', 'Beagle'), ('Poodle', 'Poodle'), ('Boxer', 'Boxer'), ('Yorkshire Terrier', 'Yorkshire Terrier'), ('Dachshund (Salsicha)', 'Dachshund (Salsicha)'), ('Bulldog Inglês', 'Bulldog Inglês'), ('Chihuahua', 'Chihuahua'), ('Shih Tzu', 'Shih Tzu'), ('Pug', 'Pug'), ('Border Collie', 'Border Collie'), ('Rottweiler', 'Rottweiler'), ('Caramelo', 'Caramelo'), ('Outra', 'Outra')], default='Outra', max_length=80),
        ),
    ]
